"""
Semantic cluster mapping for few-shot mode.

After clustering, objects that were generated by the video predictor carry
an organ_name in SegmentedObject.label (set during few-shot propagation).
This module uses majority vote to determine which cluster corresponds to
which organ, and updates all LabeledObjects accordingly.

Example:
    If cluster 3 contains 8 objects with label="left_lung" and 2 with label=None,
    then cluster 3 is mapped to "left_lung" and all its objects get that name.

Clusters without any labeled objects retain their numeric name ("cluster_N").
"""

from collections import Counter
from pathlib import Path

from project.core.data_types import LabeledObject


class ClusterSemanticMapper:
    """
    Maps cluster IDs to organ names using majority vote over labeled objects.

    Used exclusively in few-shot mode, where some SegmentedObjects carry
    organ names from the video predictor prompts.
    """

    def __init__(self):
        self._cluster_to_organ: dict[int, str] = {}

    @property
    def mapping(self) -> dict[int, str]:
        """Return the computed cluster_id -> organ_name mapping."""
        return dict(self._cluster_to_organ)

    def map(
        self,
        labeled_by_image: dict[Path, list[LabeledObject]],
    ) -> dict[Path, list[LabeledObject]]:
        """
        Compute the cluster -> organ mapping via majority vote and apply it
        to all LabeledObjects in-place.

        Parameters
        ----------
        labeled_by_image : dict[Path, list[LabeledObject]]
            All labeled objects grouped by image path.

        Returns
        -------
        dict[Path, list[LabeledObject]]
            Same structure with organ_name updated where a mapping exists.
        """
        all_labeled = [
            obj for objects in labeled_by_image.values() for obj in objects
        ]

        self._cluster_to_organ = self._compute_mapping(all_labeled)

        if self._cluster_to_organ:
            print("  Semantic cluster mapping (majority vote):")
            for cid, organ in sorted(self._cluster_to_organ.items()):
                print(f"    cluster_{cid} -> {organ}")
        else:
            print("  [WARN] No labeled objects found for semantic mapping")

        mapped_count = 0
        for objects in labeled_by_image.values():
            for obj in objects:
                if obj.organ_id in self._cluster_to_organ:
                    obj.organ_name = self._cluster_to_organ[obj.organ_id]
                    mapped_count += 1

        print(f"  Updated {mapped_count} objects with semantic names")
        return labeled_by_image

    def _compute_mapping(
        self, all_labeled: list[LabeledObject]
    ) -> dict[int, str]:
        """
        Build the cluster_id -> organ_name mapping using majority vote.

        Only objects whose SegmentedObject.label is not None participate.
        """
        cluster_votes: dict[int, Counter] = {}
        for obj in all_labeled:
            label = obj.segmented_object.label
            if label is None or obj.is_noise:
                continue

            cid = obj.organ_id
            if cid not in cluster_votes:
                cluster_votes[cid] = Counter()
            cluster_votes[cid][label] += 1

        mapping = {}
        for cid, votes in cluster_votes.items():
            winner, count = votes.most_common(1)[0]
            total_labeled = sum(votes.values())
            ratio = count / total_labeled
            print(f"    cluster_{cid}: '{winner}' wins with "
                  f"{count}/{total_labeled} votes ({ratio:.0%})")
            mapping[cid] = winner

        return mapping